import = [
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[window]
padding.x = 8
padding.y = 5
dynamic_padding = true

startup_mode = "Maximized"

decorations = "None"
decorations_theme_variant = "None"

[font]
size=14

[font.bold]
family = "Cascadia Code PL"
style = "SemiBold"

[font.bold_italic]
family = "Cascadia Code PL"
style = "SemiBold Italic"

[font.italic]
family = "Cascadia Code PL"
style = "Light Italic"

[font.normal]
family = "Cascadia Code PL"
style = "Light"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[cursor]
style.shape = "Block"
style.blinking = "On"
vi_mode_style.shape = "Block"
vi_mode_style.blinking = "Off"
